#######################
#  CRUD CONTROLLER
#######################

ZobaHolidaysManagerBundle:
  resource: "@ZobaHolidaysManagerBundle/Controller/"
  type: annotation
  prefix: 

extra_time_admin_list:
  pattern:  /extra_time_admin
  defaults: { _controller: ZobaHolidaysManagerBundle:ExtraTime:index }



#######################
#  DEFAULT CONTROLLER
#######################

holidays_index:
  pattern:  /holidays_index
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:index }

create_extra_time:
  pattern:  /create_extra_time
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:create }

update_extra_time:
  pattern:  /update_extra_time/{id}
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:create }

show_extra_time:
  pattern:  /extra_time/{id}
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:show }
  requirements:
    id:  \d+

remove_extra_time:
  pattern:  /extra_time_remove/{id}
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:remove }
  requirements:
    id:  \d+

showall_extra_time:
  pattern:  /showall_extra_time
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:showall }

clearall_extra_time:
  pattern:  /clearall_extra_time
  defaults: { _controller: ZobaHolidaysManagerBundle:Default:clearall }

#######################
#  TEST CONTROLLER
#######################

show_example_map:
  pattern:  /show_example_map
  defaults: { _controller: ZobaHolidaysManagerBundle:Test:index }
