services:
  mol.store.admin.product:
      class: Mol\StoreBundle\Admin\ProductAdmin
      tags:
          - { name: sonata.admin, manager_type: orm, group: Store, label: product }
      arguments: [null, Mol\StoreBundle\Entity\Product, SonataAdminBundle:CRUD]