imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    trust_proxy_headers:                false
    default_locale:                     %locale%
    translator:                         { fallback: it }
    secret:                             %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:                               true
    csrf_protection:                    true
    validation:                         { enable_annotations: true }
    templating:      
      engines: #assets_version: SomeVersionScheme
        - 'twig'
#      form:
#        resources:
#          - 'TaskBundle:Form'
    session:          ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%

# Assetic Configuration
assetic:
    bundles:        []
    debug:          %kernel.debug%
    use_controller: false
    # java: /usr/bin/java
    filters:
        cssrewrite: ~
        # closure:
        #     jar: %kernel.root_dir%/java/compiler.jar
        # yui_css:
        #     jar: %kernel.root_dir%/java/yuicompressor-2.4.2.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
#    user_class: Zoba\UserBundle\Entity\User
    user_class: Application\Sonata\UserBundle\Entity\User
 
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
 
        #sonata.admin_doctrine_orm.block.audit:
        #    contexts:   [admin]
 
        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:
 
        # Some specific block from the SonataMediaBundle
        #sonata.media.block.media:
        #sonata.media.block.gallery:
        #sonata.media.block.feature_media:
          
sonata_admin:
    title:      Sonata Project
    title_logo: /bundles/sonataadmin/logo_title.png
    templates:
        # default global templates
        layout:  SonataAdminBundle::standard_layout.html.twig
        ajax:    SonataAdminBundle::ajax_layout.html.twig
 
        # default actions templates, should extend a global templates
        list:    SonataAdminBundle:CRUD:list.html.twig
        show:    SonataAdminBundle:CRUD:show.html.twig
        edit:    SonataAdminBundle:CRUD:edit.html.twig
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }
        groups:
            holidays_manager:
                label: Holidays Manager

services:
    sonata.admin.extension:
        class: Application\Sonata\UserBundle\Admin\Model\UserAdmin
        tags:
#            - { name: sonata.admin.extension, target: sonata.user.admin.user }
            - { name: sonata.admin, manager_type: orm, group: Users, label: User }
        arguments: [null, Sonata\UserBundle\Entity\User, SonataUserBundle:CRUD]               

#    zoba.holidaysManager.extraTime:
#        class: Zoba\HolidaysManagerBundle\Admin\ExtraTimeAdmin;
#        tags:
#          - { name: sonata.admin, manager_type: orm, group: ExtraTimes, label: ExtraTimes }
#        arguments: [null, Zoba\HolidaysManagerBundle\Entity\ExtraTime, SonataAdminBundle:CRUD]