##########
# HOMEPAGE
##########

homepage:
    pattern:  /
    defaults: { _controller: ZobaHolidaysManagerBundle:Default:index }

################
# ZOBA BUNDLES
################

ZobaUserBundle:
    resource: "@ZobaUserBundle/Resources/config/routing.yml"
    prefix:   /

ZobaHolidaysManagerBundle:
    resource: "@ZobaHolidaysManagerBundle/Resources/config/routing.yml"
    prefix:   /

StoreBundle:
    resource: "@StoreBundle/Resources/config/routing.yml"
    prefix:   /



# Internal routing configuration to handle ESI
#_internal:
#   resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#   prefix:   /_internal
