security:
  providers:
    min_provider:
      users:
        admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
#      entity: { class:  Zoba\UserBundle\Entity\User }
        
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Zoba\UserBundle\Entity\User:
      algorithm:        sha1
      encode_as_base64: false
      iterations:       1

  role_hierarchy:
    ROLE_ADMIN:     ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern:  ^/login$
      security: false

    secured_area:
      pattern:  ^/
#      anonymous: ~
      form_login:
        login_path: /login
        check_path: /login_check
      logout:
        path:   /logout
        target: /holidays_index
        
        
        
      #http_basic:
      #  realm: "Secured Demo Area"

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
