security:
  encoders:
    FOS\UserBundle\Model\UserInterface: sha512
    Symfony\Component\Security\Core\User\User: plaintext
    Zoba\UserBundle\Entity\User:
      algorithm:        sha1
      encode_as_base64: false
      iterations:       1
      
  providers:
    chain_provider:
      providers: [in_memory, user_db]
    in_memory:
      users:
        admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }
    user_db:    
      entity: { class:  Zoba\UserBundle\Entity\User }
#    fos_userbundle:
#      entity: { class:  FOS\UserBundle\Entity\User }

  role_hierarchy:
    ROLE_ADMIN:     ROLE_USER
    ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


  firewalls:
    dev:
      pattern:  ^/(_(profiler|wdt)|css|images|js)/
      security: false

    login:
      pattern:  ^/login$
      security: false

    main:
      pattern:  ^/
#      anonymous: ~
      form_login:
#        provider: fos_userbundle
#        csrf_provider: form.csrf_provider
        login_path: /login
        check_path: /login_check
      logout:
        path:   /logout
        target: /holidays_index
        
        
        
      #http_basic:
      #  realm: "Secured Demo Area"

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
    - { path: ^/admin/, role: ROLE_ADMIN }
    #- { path: ^/_internal, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
